CREATE USER JESUS1 IDENTIFIED BY hola 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

GRANT "CONNECT" TO JESUS1;
GRANT "RESOURCE" TO JESUS1;
ALTER USER JESUS1 DEFAULT ROLE "CONNECT","RESOURCE";

GRANT UNLIMITED TABLESPACE TO JESUS1;