CREATE TABLE USUARIO (
    ID_USUARIO NUMBER,
    NOMBRES VARCHAR2(50) NOT NULL,
    APELLIDOS VARCHAR2(50) NOT NULL,
    DNI VARCHAR2(10) NOT NULL UNIQUE,
    EMAIL VARCHAR2(65) NOT NULL,
    GENERO VARCHAR2(15) NOT NULL,
    PASSWORD VARCHAR2(25) NOT NULL,
    FECHA_REG DATE NOT NULL,
    FECHA_ACT DATE,
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE ROL (
    ID_ROL NUMBER,
    NOMBRE VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL)
);

CREATE TABLE USUARIO_ROL (
    USUARIO_ID NUMBER,
    ROL_ID NUMBER,
    CONSTRAINT PK_USUARIO_ROL PRIMARY KEY (USUARIO_ID, ROL_ID),
    CONSTRAINT FK_USUARIO_ROL_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROL_ROL FOREIGN KEY (ROL_ID) REFERENCES ROL(ID_ROL)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER,
    NOMBRE VARCHAR2(30) NOT NULL,
    DESCRIPCION VARCHAR2(45) NOT NULL,
    FECHA_REG DATE NOT NULL,
    FECHA_ACT DATE,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER,
    CATEGORIA_ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(35) NOT NULL,
    DESCRIPCION VARCHAR2(50) NOT NULL,
    IMAGEN VARCHAR2(255) NOT NULL,
    PRECIO NUMBER NOT NULL,
    STOCK NUMBER NOT NULL,
    FECHA_REG DATE NOT NULL,
    FECHA_ACT DATE,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE PROFORMA (
    ID_PROFORMA NUMBER,
    USUARIO_ID NUMBER NOT NULL,
    PRODUCTO_ID NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    STATUS VARCHAR2(25) NOT NULL,
    FECHA_REG DATE NOT NULL,
    CONSTRAINT PK_PROFORMA PRIMARY KEY (ID_PROFORMA),
    CONSTRAINT FK_PROFORMA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_PROFORMA_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO)
);

CREATE TABLE PAGO (
    ID_PAGO NUMBER,
    USUARIO_ID NUMBER NOT NULL,
    NOMBRE_TARJETA VARCHAR2(55) NOT NULL,
    NUMERO_TARJETA VARCHAR2(30) NOT NULL,
    MONTO_TOTAL NUMBER NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO),
    CONSTRAINT FK_PAGO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER,
    USUARIO_ID NUMBER NOT NULL,
    PAGO_ID NUMBER NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_PEDIDO_PAGO FOREIGN KEY (PAGO_ID) REFERENCES PAGO(ID_PAGO)
);

CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE_PEDIDO NUMBER,
    PEDIDO_ID NUMBER NOT NULL,
    PRODUCTO_ID NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO NUMBER NOT NULL,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (ID_DETALLE_PEDIDO),
    CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO)
);